Repository DishpitDev/Slopify, pull requests merged in 2024-12, with the labels that each got.

#8 Stockify
  index.html
  static/images/wojak_stock_down.gif
  static/images/wojak_stock_up.webp
Labels: enhancement

#9 add contrib doc
  CONTRIBUTING
Labels: documentation

#13 Smooth jazz saxophone solo with a lowfi vibe
  index.html
  static/js/index.js
Labels: enhancement

#19 feat: Add Web1
  index.html
  static/images/800x600.gif
  static/images/aol-sucks.gif
  static/images/bestview.gif
  static/images/w95link.gif
Labels: enhancement

#16 Important additions
  index.html
Labels: enhancement

#1 added top tier enterprise security features
  index.html
  security.js
Labels: enhancement

#22 Make The Vibing Frog Dance
  index.html
  package-lock.json
  static/js/index.js
Labels: enhancement

#23 random shader from shadertoy
  index.html
Labels: enhancement

#27 skip to content
  index.html
Labels: enhancement

#28 a Slopify logo.
  SlopifyLogo.png
Labels: enhancement

#30 Feat/integrate logo
  CONTRIBUTING.md
  README.md
  index.html
Labels: enhancement

#29 Surprise customer with a beautiful color scheme
  index.html
  static/js/index.js
Labels: enhancement

#18 feat: add hitcounter
  index.html
Labels: enhancement

#14 Add Embr Web IDE
  embr/embr.js
  embr/embr.wasm
  embr/index.html
  index.html
Labels: enhancement

#31 useful links section
  index.html
Labels: enhancement

#33 feat: spinning donut
  donut.js
  index.html
Labels: enhancement

#35 add lowtiergod image to footer
  index.html
  static/images/lowtiergod.gif
Labels: enhancement

#36 add frog wisdom feature with speech synthesis and quotes
  index.html
  static/js/index.js
  static/js/quotes.json
Labels: enhancement

#38 Feat: Add in even better website link
  index.html
Labels: enhancement

#39 Spinning donut but in Elle:tm:
  donut.le
Labels: enhancement

#40 rick vibes
  index.html
  static/images/favicon.ico
  static/images/rick.gif
  static/js/index.js
Labels: enhancement

#42 Replaced the bitcoin frog with someone more pleasant
  static/images/frog.webp
Labels: enhancement

#43 add don't ask to ask, just ask
  index.html
Labels: enhancement

#44 add vibe button back
  static/js/index.js
Labels: enhancement

#45 Konami Code
  index.html
Labels: enhancement

#50 add twittermoanials
  index.html
Labels: enhancement

#41 add pussy
  index.html
Labels: enhancement

#47 Add a random surprise for every (68+1)th user
  index.html
  static/audio/protocol.mp3
  static/images/handsome.jpg
Labels: enhancement

#48 fix some issues
  index.html
  static/js/index.js
  static/js/quotes.json
Labels: enhancement

#53 add a chat page
  chat.html
  index.html
  static/js/tunnel_lib.js
Labels: enhancement

#54 Update index.html to add Rainbow Cursor Trail
  index.html
Labels: enhancement

#58 Add "click me!" button
  index.html
Labels: enhancement

#80 unique chat name + relloc
  chat.html
Labels: bug, enhancement

#65 Added the goodest girl.jpeg
  index.html
  static/images/bobi.jpg
Labels: enhancement

#15 Let Elon fly!
  flappyMusk.js
  index.html
  static/images/elon_head.jpeg
Labels: enhancement

#72 Added Penguin to Home Page
  index.html
  static/images/penguin.webp
Labels: enhancement

#87 Marisa touhou styled oneko mouse follower
  index.html
  static/images/come_here_marisa_kirisame.gif
  static/images/monster_zero_ultra.jpg
  static/images/oneko/oneko-classic.png
  static/images/oneko/oneko-dog.png
  static/images/oneko/oneko-marisa_a.png
  static/js/oneko.js
Labels: enhancement

#104 i added looping music to the alan becker page because i love improvin…
  second.html
  static/images/alanbecker/audio/wtf.mp3
Labels: enhancement

#102 chat dark mode and buttons old
  chat.html
Labels: enhancement

#112 add things to chat
  chat.html
  static/audio/youvegotmail.mp3
  static/images/4db62b6a70d285b0efb299ee6816504e.jpg
Labels: enhancement

#116 fix: add fennec fox pictures
  static/images/cute.jpg
  static/images/snarl.jpg
Labels: bug, enhancement

#125 add bot tag v2
  chat.html
Labels: bug, enhancement

#130 blame github
  chat.html
Labels: bug, enhancement

#139 add button to owoify the page's text
  index.html
Labels: enhancement

#140 Add page nav
  index.html
  static/css/page-nav.css
Labels: enhancement

#141 remove seizure inducing effects
  index.html
Labels: enhancement

#144 Added an animated svg of a skibidi toilet head to the secondary site.
  second.html
  static/images/skibidi.svg
Labels: enhancement

#127 feat(chat): add blur mode for image filter
  chat.html
Labels: enhancement

#150 Update index.html
  index.html
Labels: enhancement

#179 Fix to page exploding
  index.html
Labels: bug

#180 Funny labels
  chat.html
Labels: enhancement

#84 The sun is a deadly lazer.
  index.html
  static/audio/deadly.mp3
  static/audio/no.mp3
  static/images/deadly.gif
  static/images/deadly.png
  static/images/sun.png
Labels: enhancement

#145 Update flappyMusk.js to better fit the ability to read
  flappyMusk.js
Labels: enhancement

#149 Code quality is what distinguishes a 10x engineer from a bunch of bad ones
  src/main.rs
Labels: documentation

#153 added bouncy calebs
  bouncy-caleb.js
  index.html
  static/images/caleb.webp
Labels: enhancement

#155 add an image of a raccoon
  index.html
  static/images/raccoon.jpg
Labels: enhancement

#156 Deflated Musk's ego and made him more gay
  flappyMusk.js
  index.html
Labels: enhancement

#160 dvd bounce
  index.html
  static/images/DVD_logo.png
Labels: enhancement

#164 feat: add healthcheck endpoint
  health-check.html
Labels: enhancement

#137 Update index.html
  index.html
Labels: enhancement

#172 Add message highlights when mentioned / bugfix
  chat.html
Labels: enhancement

#175 Gain perspective
  index.html
Labels: enhancement

#184 Add LIVE-SERVER and update README.md and CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
  package-lock.json
  package.json
Labels: documentation

#186 Update quotes.json
  static/js/quotes.json
Labels: enhancement

#188 feat: brainrot playlist
  index.html
Labels: enhancement

#189 my diary!!
  index.html
  mizdiary.html
Labels: enhancement

#187 ✨emojis now mandatory in commit messages ✨
  .husky/commit-msg
  .husky/commit-msg.js
  package-lock.json
  package.json
Labels: enhancement

#192 added the shake effect to all mouseovers
  index.html
Labels: enhancement

#196 add playable doom wadcmd
  index.html
Labels: enhancement

#197 add more clear slopchat button
  index.html
  static/images/slopchat.jpg
Labels: enhancement

#198 fix
  index.html
Labels: bug, enhancement

#194 Added touhouproject.html
  index.html
  static/images/touhouproject/BTD6Truthers.jpg
  static/images/touhouproject/ReimufindsChrist.png
  static/images/touhouproject/badapple.gif
  static/images/touhouproject/byakurengradient.webp
  static/images/touhouproject/chirumiru-cirno.gif
  static/images/touhouproject/fumo.png
  static/images/touhouproject/fumocomputer.jpg
  static/images/touhouproject/holdthiscard.jpg
  static/images/touhouproject/hypothetically.jpg
  static/images/touhouproject/somad.jpeg
  static/images/touhouproject/touhou-just-dodge.gif
  touhouproject.html
Labels: enhancement

#227 Slopify App
  Slopify/.gitignore
  Slopify/.vscode/extensions.json
  Slopify/README.md
  Slopify/package-lock.json
  Slopify/package.json
  Slopify/src-tauri/.gitignore
  Slopify/src-tauri/Cargo.lock
  Slopify/src-tauri/Cargo.toml
  Slopify/src-tauri/build.rs
  Slopify/src-tauri/capabilities/default.json
  Slopify/src-tauri/icons/128x128.png
  Slopify/src-tauri/icons/128x128@2x.png
  Slopify/src-tauri/icons/32x32.png
  Slopify/src-tauri/icons/Square107x107Logo.png
  Slopify/src-tauri/icons/Square142x142Logo.png
  Slopify/src-tauri/icons/Square150x150Logo.png
  Slopify/src-tauri/icons/Square284x284Logo.png
  Slopify/src-tauri/icons/Square30x30Logo.png
  Slopify/src-tauri/icons/Square310x310Logo.png
  Slopify/src-tauri/icons/Square44x44Logo.png
  Slopify/src-tauri/icons/Square71x71Logo.png
  Slopify/src-tauri/icons/Square89x89Logo.png
  Slopify/src-tauri/icons/StoreLogo.png
  Slopify/src-tauri/icons/icon.icns
  Slopify/src-tauri/icons/icon.ico
  Slopify/src-tauri/icons/icon.png
  Slopify/src-tauri/src/lib.rs
  Slopify/src-tauri/src/main.rs
  Slopify/src-tauri/tauri.conf.json
  Slopify/src/assets/javascript.svg
  Slopify/src/assets/tauri.svg
  Slopify/src/index.html
  Slopify/src/main.js
  Slopify/src/styles.css
Labels: enhancement

#131 Add 'Call in Randy Pitchford' button
  index.html
  static/images/randypitchford/badass.jpg
  static/images/randypitchford/dukenukem.jpg
  static/images/randypitchford/genderbent.jpg
  static/images/randypitchford/outside.jpg
  static/images/randypitchford/selfie.jpg
Labels: enhancement

#183 Astolfo hmhm
  astolfo.html
  astolfo.js
  index.html
  static/images/astolfo/astolfo1.jpg
  static/images/astolfo/astolfo10.jpg
  static/images/astolfo/astolfo11.jpg
  static/images/astolfo/astolfo2.jpg
  static/images/astolfo/astolfo3.jpg
  static/images/astolfo/astolfo4.jpg
  static/images/astolfo/astolfo5.jpg
  static/images/astolfo/astolfo6.jpg
  static/images/astolfo/astolfo7.jpg
  static/images/astolfo/astolfo8.jpg
  static/images/astolfo/astolfo9.jpg
  static/images/astolfo/hq720.jpg
Labels: enhancement

#205 Update `README.md` to better reflect the educational value of Slopify.dev
  README.md
Labels: documentation

#206 Emoji regex fix 🔍
  .husky/commit-msg
  .husky/commit-msg.js
  all-emojis.txt
  emoji-square.js
  package-lock.json
  package.json
Labels: enhancement

#207 expounded in detail about the most important features
  README.md
Labels: documentation

#215 ᗜˬᗜ
  index.html
  static/audio/baka.mp3
  static/images/touhouproject/baka.png
Labels: enhancement

#216 SUPPORT A CREATOR
  index.html
Labels: enhancement

#220 Adding the Huzz Button
  index.html
Labels: enhancement

#222 added button that will delete all of the html elements
  index.html
Labels: enhancement

#230 ✨✨THE LEADERBOARD✨✨
  index.html
  public/leader_board_tunnel.js
  public/leaderboard.html
Labels: enhancement

#244 HOTFIX: Purge Leaderboard
  index.html
  public/leader_board_tunnel.js
  public/leaderboard.html
Labels: bug

#241 fix styles 💅
  index.html
Labels: enhancement

#240 add hot singles near you popup, more additions planned :3
  index.html
Labels: enhancement

#195 Added god.html (Fernando Alonso)
  god.html
  index.html
  static/video/fernandoAlonso.mp4
Labels: enhancement

#217 added comic sans button
  index.html
  static/fonts/Comic Sans MS.ttf
Labels: enhancement

#234 Mention an overlooked critical feature
  README.md
Labels: documentation

#209 Small refactor
  chat.html
  index.html
  package-lock.json
  static/css/chatbot.css
  static/css/comicButton.css
  static/css/flappyMusk.css
  static/css/hamburgerMenu.css
  static/css/news.css
  static/css/security.css
  static/css/style.css
  static/js/8ball.js
  static/js/badApple.js
  static/js/bouncy-caleb.js
  static/js/buttons.js
  static/js/chatbot.js
  static/js/cirno.js
  static/js/clickMeBtn.js
  static/js/comicButton.js
  static/js/cookieClick.js
  static/js/cursorTrails.js
  static/js/donut.js
  static/js/dvdBounce.js
  static/js/epic.js
  static/js/fishtank.js
  static/js/fishtank_loader.js
  static/js/flappyMusk.js
  static/js/gl.js
  static/js/hamburgerMenu.js
  static/js/huzzButton.js
  static/js/killEverything.js
  static/js/konami.js
  static/js/makeWoke.js
  static/js/mandelbrot_uwu.js
  static/js/onion.js
  static/js/owoifyPage.js
  static/js/pageLoadUwUSound.js
  static/js/rainbowPulse.js
  static/js/randyifier.js
  static/js/security.js
  static/js/securityLoader.js
  static/js/shadertoyLoader.js
  static/js/shakeTarget.js
  static/js/stocks.js
  static/js/sun.js
  static/js/surprise.js
  static/js/worseTheme.js
Labels: enhancement

#232 fix: package.json
  bun.lockb
Labels: enhancement

#250 ✨✨LEADERBOARD 2: WONT BREAK PROD EDITION✨✨
  index.html
  lbtunnel.js
  leaderboard.html
  vercel.json
Labels: enhancement

#259 Slopify App
  README.md
  Slopify/README.md
  Slopify/index.html
  Slopify/package-lock.json
  Slopify/package.json
  Slopify/public/tauri.svg
  Slopify/public/vite.svg
  Slopify/src-tauri/Cargo.lock
  Slopify/src-tauri/tauri.conf.json
  Slopify/src/App.jsx
  Slopify/src/assets/javascript.svg
  Slopify/src/assets/react.svg
  Slopify/src/components/LoginForm.jsx
  Slopify/src/components/MessageForm.jsx
  Slopify/src/components/MessageList.jsx
  Slopify/src/components/RegisterForm.jsx
  Slopify/src/index.html
  Slopify/src/main.js
  Slopify/src/main.jsx
  Slopify/src/pages/ChatPage.jsx
  Slopify/src/pages/HomePage.jsx
  Slopify/src/styles.css
  Slopify/src/styles/HomePage.css
  Slopify/src/styles/global.css
  Slopify/src/supabaseClient.js
  Slopify/vite.config.js
Labels: enhancement

#203 seizuring rotating GOAT.png
  index.html
  static/images/RotatingGoat.png
Labels: enhancement

#221 🛡Add protection against accidentally typing forbidden words🛡
  index.html
  static/js/hellProtection.js
Labels: enhancement

#235 ad blocker detection, additional cookie banners, and crypto integration
  blocked.gif
  index.html
  rightad.js
Labels: enhancement

#270 Slopify App Analytics
  Slopify/index.html
  Slopify/src-tauri/tauri.conf.json
Labels: enhancement
