Repository DishpitDev/Slopify, pull requests merged in 2025-01, with the labels that each got.

#228 🤖 MAJOR FEATURE: SlopBot 🤖
  ai.html
  index.html
  static/css/slopbot.css
Labels: enhancement

#132 Merge adjacent texts into single span and decrease emoji size
  chat.html
Labels: enhancement

#287 Add custom emojis to chat
  chat.html
  static/images/emojis/ayaya.png
  static/images/emojis/clueless.png
  static/images/emojis/dopepe.png
  static/images/emojis/dread.png
  static/images/emojis/endMe.png
  static/images/emojis/feelsBadMan.png
  static/images/emojis/kekw.png
  static/images/emojis/laughingPepe.png
  static/images/emojis/lfg.png
  static/images/emojis/minipog.png
  static/images/emojis/monkaGiga.png
  static/images/emojis/monkaS.png
  static/images/emojis/monkaSnake.png
  static/images/emojis/pogU.png
  static/images/emojis/pooga.png
  static/images/emojis/superkek.png
  static/images/emojis/thonk.png
  static/images/emojis/weirdga.png
Labels: enhancement

#285 Update 404 Page
  .gitignore
  404.html
  README.md
  static/css/mediaPlayer.css
  static/js/mediaPlayer.js
Labels: enhancement

#297 Create games page, close #247
  games/index.html
  games/katamari.html
  games/nesemulator.html
  index.html
  static/InterglacticTransmissing.nes
  static/css/world_map/styles.css
  static/js/flappyMusk.js
  static/js/katamari-loader.js
  static/js/katamari.js
  static/js/nes-embed.js
Labels: sloptimization

#302 Quickfix
  .github/workflows/emoji-check.yml
  .github/workflows/rizz-check.yml
  LICENSE.md
  static/InterglacticTransmissing.nes
  static/js/nes-embed.js
  static/video/ganondorf_laugh.mp4
  static/video/wombo_combo.mp4
Labels: sloptimization

#304 add new chat
  chat.html
  chatroom.html
  index.html
Labels: slop

#308 Feat/profile color
  Slopify/package-lock.json
  Slopify/package.json
  Slopify/src/components/MessageList.jsx
  Slopify/src/components/RegisterForm.jsx
Labels: slop

#309 fanum tax 🍆
  .husky/commit-msg
  .husky/commit-msg.js
  .prettierignore
  Slopify/package-lock.json
  Slopify/package.json
  Slopify/src/components/MessageList.jsx
  Slopify/src/components/RegisterForm.jsx
  Slopify/src/styles/global.css
  chat.html
  chatroom.html
  games/index.html
  games/nesemulator.html
  games/snake.html
  health-check.html
  index.html
  package.json
  static/css/cl-showpos.css
  static/css/luxembourg.css
  static/css/snake.css
  static/css/style.css
  static/js/dyslexia.js
  static/js/epicPhysics.js
  static/js/index.js
  static/js/jGravity.js
  static/js/jquery172.js
  static/js/luxembourg.js
  static/js/nes-embed.js
  static/js/poeskatAnimation.js
  static/js/quotes.json
  static/js/reverseScroll.js
  static/js/snake.js
  static/js/wednesday.js
  static/js/xterm.js
  tv.html
  uwu.html
Labels: slop

#313 DESKTOP: Component Breakdown and Chat Fixes
  Slopify/src-tauri/tauri.conf.json
  Slopify/src/App.jsx
  Slopify/src/components/Button.jsx
  Slopify/src/components/LoginForm.jsx
  Slopify/src/components/Message.jsx
  Slopify/src/components/MessageForm.jsx
  Slopify/src/components/MessageList.jsx
  Slopify/src/components/RegisterForm.jsx
  Slopify/src/pages/ChatPage.jsx
  Slopify/src/pages/HomePage.jsx
  Slopify/src/styles/HomePage.css
  Slopify/src/styles/global.css
Labels: slop

#314 basic slopbox implementation
  Slopify/src/App.jsx
  Slopify/src/pages/ChatPage.jsx
  Slopify/src/pages/Slopbox.jsx
Labels: slop

#316 fix message in wrong place
  Slopify/src/components/MessageList.jsx
Labels: sloptimization

#317 Make mouse click more explosive💥
  index.html
  kaboomtest.html
  static/audio/kaboom.mp3
  static/css/kaboom.css
  static/images/kaboom.png
  static/js/kaboom.js
Labels: slop

#318 Add back dylsexia fliter
  index.html
Labels: slop

#319 fix slopTV (again)
  index.html
  static/css/style.css
Labels: slop

#321 Profile and Settings Page
  Slopify/src/App.jsx
  Slopify/src/components/Message.jsx
  Slopify/src/components/MessageList.jsx
  Slopify/src/pages/ChatPage.jsx
  Slopify/src/pages/ProfilePage.jsx
Labels: slop

#337 updates
  Slopify/src-tauri/tauri.conf.json
  Slopify/src/pages/ProfilePage.jsx
  calc.html
  games/snake.html
  index.html
  package.json
  static/audio/fart.mp3
  static/audio/sigma.mp3
  static/audio/skippidy.mp3
  static/css/chatbot.css
  static/css/style.css
  static/images/Clippy.png
  static/images/calc/0.gif
  static/images/calc/1.gif
  static/images/calc/2.webp
  static/images/calc/3.gif
  static/images/calc/4.gif
  static/images/calc/5.gif
  static/images/calc/6.gif
  static/images/calc/7.gif
  static/images/calc/8.gif
  static/images/calc/9.gif
  static/images/calc/clear.gif
  static/images/calc/decimal.webp
  static/images/calc/divide.gif
  static/images/calc/equals.gif
  static/images/calc/math.gif
  static/images/calc/maths.gif
  static/images/calc/minus.gif
  static/images/calc/plusmult.gif
  static/images/coconut.jpg
  static/js/badApple.js
  static/js/catgirl.js
  static/js/chatbot.js
  static/js/cirno.js
  static/js/coconut-check.js
  static/js/comicButton.js
  static/js/cookieBanners.js
  static/js/crypto_wallet.js
  static/js/dvdBounce.js
  static/js/dyslexia.js
  static/js/epic.js
  static/js/icey-oneko.js
  static/js/kaboom.js
  static/js/main.js
  static/js/mandelbrot_uwu.js
  static/js/oneko.js
  static/js/randyifier.js
  static/js/reverseScroll.js
  static/js/shadertoyLoader.js
  static/js/shakeTarget.js
  static/js/surprise.js
  static/js/twittermoanials.js
  static/js/win2k.js
  static/js/world_map.js
  static/js/xterm.js
Labels: slop

#371 S0 - D1
  LIVE/.gitignore
  LIVE/.htmlhintrc
  LIVE/.npmrc
  LIVE/.stylelintrc.json
  LIVE/MDMCK10's worst nightmare.html
  LIVE/assets/css/bulma.min.css
  LIVE/cookie/opt-out/index.html
  LIVE/eslint.config.mjs
  LIVE/index.html
  LIVE/package.json
  LIVE/src/static/css/main.css
  LIVE/src/static/js/speech.js
  LIVE/trolololo.mp3
  LIVE/tv/hls.min.js
  LIVE/tv/index.html
  LIVE/tv/tv_audio/546047__grcekh__analog-crt-tv-electronic-static-noise.m4a
  LIVE/tv/tv_menu.js
  LIVE/tv/tv_script.js
  LIVE/tv/tv_style.css
  styles.css
Labels: feat

#370 Added IP address popup and button back to season0
  LIVE/favicon.ico
  LIVE/index.html
  LIVE/src/static/css/ip.css
  LIVE/src/static/js/ip.js
Labels: feat

#372 fix scripts
  LIVE/index.html
Labels: bug

#381 fix html tags, formatting
  .vscode/settings.json
  LIVE/.vscode
  LIVE/index.html
Labels: feat

#384 Require all files changed by pull requests to pass HTML/CSS validation
  .github/workflows/ensure-valid-html-css.yml
Labels: feat

#386 fixing some formatting
  LIVE/cloud/index.html
  LIVE/index.html
Labels: shitpost

#374 added slopwind (tailwind) support
  LIVE/index.html
  LIVE/package.json
  LIVE/postcss.config.js
  LIVE/src/static/css/tailwind.css
  LIVE/src/style.css
  LIVE/tailwind.config.js
Labels: feat

#413 Contributors list
  .github/workflows/update-contributors.yml
  README.md
  fetch-contributors.py
  index.html
  script.js
  styles.css
Labels: feat

#379 feat: add niko oneshot
  LIVE/index.html
  LIVE/src/static/css/niko_oneshot.css
  LIVE/src/static/img/nikos/1.png
  LIVE/src/static/img/nikos/10.png
  LIVE/src/static/img/nikos/11.png
  LIVE/src/static/img/nikos/12.png
  LIVE/src/static/img/nikos/13.png
  LIVE/src/static/img/nikos/14.png
  LIVE/src/static/img/nikos/2.png
  LIVE/src/static/img/nikos/3.png
  LIVE/src/static/img/nikos/4.png
  LIVE/src/static/img/nikos/5.png
  LIVE/src/static/img/nikos/6.png
  LIVE/src/static/img/nikos/7.png
  LIVE/src/static/img/nikos/8.png
  LIVE/src/static/img/nikos/9.png
  LIVE/src/static/js/niko_oneshot.js
Labels: feat
